//! Deterministic engine fixtures for downstream integration tests.
//!
//! This module is available only through the `test-support` feature. It builds
//! the outcomes through the real engine boundary, so adapter tests do not need
//! to manufacture sealed candidates, risk quotes, or broker transitions.

use std::collections::BTreeMap;

use rust_decimal::Decimal;

use crate::book::OrderBook;
use crate::broker::{BrokerConfig, BrokerRunContext, ExitReason, PaperBroker};
use crate::domain::{
    Bps, EventId, LedgerId, Leverage, Market, Price, Quantity, RunId, Side, Sleeve, Usdc,
};
use crate::event::{BookLevel, BookSnapshot, DurationNs, FundingRate, MarketEvent, TimestampNs};
use crate::ledger::LedgerState;
use crate::risk::liquidation::{MaintenanceTier, MaintenanceTiers};
use crate::risk::sizing::{
    ConservativeCosts, ImpactBand, ImpactCurve, RiskLimits, RiskRequest, RiskSnapshot,
    VenueConstraints,
};
use crate::strategy::{
    CandidateSpecification, CostDecision, CostQuote, OrderIntent, SignalCandidate, Strategy,
    StrategyKind,
};
use crate::universe::{
    DepthProfile, HistoryQuality, ListingState, MarketDataAvailability, SidedDepth,
    UniverseCandidate, UniverseLiquidity, UniverseSelector,
};

use super::{
    Engine, EngineContext, EngineEvent, EngineOutcome, EngineState, EntryCandidate, EventAdmission,
    SnapshotBindings, StrategyFingerprints, canonical_snapshot,
};

const RULES_FINGERPRINT: &str = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
const BASE_TIME_NS: i128 = 900_000_000_000;

/// One real engine outcome with its normalized source-event evidence.
pub struct LifecycleFixture {
    event_id: &'static str,
    event_time_ns: i64,
    kind: &'static str,
    payload_json: &'static str,
    outcome: EngineOutcome,
}

impl LifecycleFixture {
    /// Stable causal source-event identity.
    #[must_use]
    pub const fn event_id(&self) -> &'static str {
        self.event_id
    }

    /// Authoritative source/venue time retained with the raw source event.
    #[must_use]
    pub const fn event_time_ns(&self) -> i64 {
        self.event_time_ns
    }

    /// Normalized source-event kind.
    #[must_use]
    pub const fn kind(&self) -> &'static str {
        self.kind
    }

    /// Normalized source-event payload.
    #[must_use]
    pub const fn payload_json(&self) -> &'static str {
        self.payload_json
    }

    /// Actual transition generated by [`Engine::apply`].
    #[must_use]
    pub const fn outcome(&self) -> &EngineOutcome {
        &self.outcome
    }
}

/// Produces real partial-exit, signed-funding, and capped-liquidation outcomes.
///
/// These fixtures exist solely to make downstream persistence integration tests
/// exercise the complete engine-to-adapter boundary without widening the
/// production constructors for sealed strategy and risk values.
#[must_use]
pub fn critical_lifecycle_fixtures() -> Vec<LifecycleFixture> {
    let at = timestamp(BASE_TIME_NS);
    let context = context(at);
    let market = Market::new("BTC").expect("fixture market must be valid");

    let partial_request_at = timestamp(BASE_TIME_NS + 2);
    let exiting = Engine::apply(
        EngineEvent::ExitRequested {
            event_id: event_id("fixture-partial-exit-request"),
            at: partial_request_at,
            reason: ExitReason::Strategy,
            market: market.clone(),
            price: price(100),
            event_time: partial_request_at,
            received_at: partial_request_at,
        },
        opened_btc_state(at),
        &context,
    )
    .expect("fixture exit request must apply")
    .into_parts()
    .0;
    let partial_source_at = timestamp(BASE_TIME_NS + 2);
    let partial_at = timestamp(BASE_TIME_NS + 3);
    let partial = Engine::apply(
        EngineEvent::ExecutableBook {
            event_id: event_id("fixture-partial-exit-book"),
            at: partial_at,
            book: book_with_source_time(
                market.clone(),
                partial_source_at,
                partial_at,
                2,
                99,
                100,
                decimal(1, 1),
            ),
        },
        exiting,
        &context,
    )
    .expect("fixture partial exit must apply");

    let debit_source_at = timestamp(BASE_TIME_NS + 2);
    let debit_at = timestamp(BASE_TIME_NS + 3);
    let debit = funding_outcome(
        "fixture-funding-debit",
        debit_source_at,
        debit_at,
        decimal(1, 3),
        opened_btc_state(at),
        &context,
    );

    let credit_source_at = timestamp(BASE_TIME_NS + 3);
    let credit_at = timestamp(BASE_TIME_NS + 4);
    let debit_predecessor = funding_outcome(
        "fixture-funding-credit-predecessor",
        debit_source_at,
        debit_at,
        decimal(1, 3),
        opened_btc_state(at),
        &context,
    )
    .into_parts()
    .0;
    let credit = funding_outcome(
        "fixture-funding-credit",
        credit_source_at,
        credit_at,
        decimal(-1, 3),
        debit_predecessor,
        &context,
    );

    let mark_at = timestamp(BASE_TIME_NS + 2);
    let liquidation_pending = Engine::apply(
        EngineEvent::MarketMark {
            event_id: event_id("fixture-liquidation-mark"),
            at: mark_at,
            market: market.clone(),
            price: price(80),
            event_time: mark_at,
            received_at: mark_at,
        },
        opened_btc_state(at),
        &context,
    )
    .expect("fixture liquidation trigger must apply")
    .into_parts()
    .0;
    let liquidation_at = timestamp(BASE_TIME_NS + 3);
    let liquidation = Engine::apply(
        EngineEvent::ExecutableBook {
            event_id: event_id("fixture-liquidation-gap-book"),
            at: liquidation_at,
            book: book_with_source_time(market, mark_at, liquidation_at, 2, 70, 71, decimal(10, 0)),
        },
        liquidation_pending,
        &context,
    )
    .expect("fixture capped liquidation must apply");

    vec![
        LifecycleFixture {
            event_id: "fixture-partial-exit-book",
            event_time_ns: BASE_TIME_NS as i64 + 2,
            kind: "executable_book",
            payload_json: r#"{"fixture":"partial_exit","market":"BTC"}"#,
            outcome: partial,
        },
        LifecycleFixture {
            event_id: "fixture-funding-debit",
            event_time_ns: BASE_TIME_NS as i64 + 2,
            kind: "funding_observed",
            payload_json: r#"{"fixture":"funding_debit","market":"BTC"}"#,
            outcome: debit,
        },
        LifecycleFixture {
            event_id: "fixture-funding-credit",
            event_time_ns: BASE_TIME_NS as i64 + 3,
            kind: "funding_observed",
            payload_json: r#"{"fixture":"funding_credit","market":"BTC"}"#,
            outcome: credit,
        },
        LifecycleFixture {
            event_id: "fixture-liquidation-gap-book",
            event_time_ns: BASE_TIME_NS as i64 + 2,
            kind: "executable_book",
            payload_json: r#"{"fixture":"capped_liquidation","market":"BTC"}"#,
            outcome: liquidation,
        },
    ]
}

fn funding_outcome(
    id: &str,
    venue_at: TimestampNs,
    as_of_at: TimestampNs,
    rate: Decimal,
    state: EngineState,
    context: &EngineContext,
) -> EngineOutcome {
    Engine::apply(
        EngineEvent::FundingObserved {
            event_id: event_id(id),
            at: as_of_at,
            market: Market::new("BTC").expect("fixture market must be valid"),
            venue_at,
            received_at: as_of_at,
            rate: FundingRate::new(rate),
            mark_price: price(100),
        },
        state,
        context,
    )
    .expect("fixture funding must apply")
}

/// Builds an actual BTC paper position for adapter integration tests.
///
/// The position is opened only through the real sealed-entry and executable-
/// book engine paths; production code cannot construct it directly.
#[must_use]
pub fn opened_btc_state(at: TimestampNs) -> EngineState {
    let strategy = AcceptAll;
    let context = context(at);
    let queued = apply_entry(
        event_id("fixture-open-queue"),
        at,
        vec![EntryCandidate::new(
            candidate("BTC", decimal(3, 2), at),
            &strategy,
        )],
        state(at),
        &context,
    )
    .expect("fixture entry must queue")
    .into_parts()
    .0;
    let recovered = Engine::apply(
        EngineEvent::MarketRecovered {
            event_id: event_id("fixture-open-recovery"),
            at,
            market: Market::new("BTC").expect("fixture market must be valid"),
        },
        queued,
        &context,
    )
    .expect("fixture recovery must apply")
    .into_parts()
    .0;
    let fill_at = timestamp(i128::from(at.value()) + 1);
    Engine::apply(
        EngineEvent::ExecutableBook {
            event_id: event_id("fixture-open-book"),
            at: fill_at,
            book: book(
                Market::new("BTC").expect("fixture market must be valid"),
                fill_at,
            ),
        },
        recovered,
        &context,
    )
    .expect("fixture entry fill must apply")
    .into_parts()
    .0
}

fn apply_entry<'strategy>(
    event_id: EventId,
    at: TimestampNs,
    candidates: Vec<EntryCandidate<'strategy>>,
    state: EngineState,
    context: &EngineContext,
) -> Result<EngineOutcome, super::EngineError> {
    let snapshot = canonical_snapshot(&state, &event_id, at, &candidates, context)?;
    Engine::apply(
        EngineEvent::entry_arbitration(event_id, at, snapshot, candidates),
        state,
        context,
    )
}

fn state(at: TimestampNs) -> EngineState {
    let policies = ["BTC", "ETH"]
        .into_iter()
        .map(|market| {
            (
                Market::new(market).expect("fixture market must be valid"),
                policy_for(market, at),
            )
        })
        .collect();
    EngineState::new(
        LedgerState::new(LedgerId::RulesOnly, at).expect("fixture ledger must open"),
        broker(at),
        policies,
    )
}

fn broker(at: TimestampNs) -> PaperBroker {
    PaperBroker::new(
        BrokerConfig::new(
            usdc(1),
            DurationNs::new(1_000).expect("fixture duration must be valid"),
        )
        .expect("fixture broker config must be valid"),
        BrokerRunContext::new(
            RunId::new("fixture-paper-run").expect("fixture run ID must be valid"),
            digest('a'),
            digest('b'),
        )
        .expect("fixture broker context must be valid"),
        at,
    )
}

fn policy_for(market: &str, at: TimestampNs) -> crate::risk::sizing::RiskPolicy {
    let market = Market::new(market).expect("fixture market must be valid");
    let snapshot = RiskSnapshot::new(
        at,
        at,
        usdc(100),
        digest('a'),
        book(market, at).commitment_digest(),
        digest('c'),
        digest('d'),
        digest('e'),
    )
    .expect("fixture risk snapshot must be valid");
    request(at).with_snapshot(snapshot).into_policy()
}

fn context(at: TimestampNs) -> EngineContext {
    let books = ["BTC", "ETH"]
        .into_iter()
        .map(|market| {
            let market = Market::new(market).expect("fixture market must be valid");
            (market.clone(), book(market, at))
        })
        .collect::<BTreeMap<_, _>>();
    EngineContext::new(
        EventAdmission::New,
        SnapshotBindings::new(books, active_universe(at)),
        StrategyFingerprints::new(RULES_FINGERPRINT, digest('g')),
    )
}

fn book(market: Market, at: TimestampNs) -> OrderBook {
    book_with_prices(market, at, 1, 99, 100, decimal(10, 0))
}

fn book_with_prices(
    market: Market,
    at: TimestampNs,
    sequence: u64,
    bid: i64,
    ask: i64,
    quantity: Decimal,
) -> OrderBook {
    book_with_source_time(market, at, at, sequence, bid, ask, quantity)
}

fn book_with_source_time(
    market: Market,
    source_at: TimestampNs,
    received_at: TimestampNs,
    sequence: u64,
    bid: i64,
    ask: i64,
    quantity: Decimal,
) -> OrderBook {
    let event = MarketEvent::book_snapshot(
        source_at,
        received_at,
        market,
        BookSnapshot::new(
            sequence,
            vec![BookLevel::new(price(bid), quantity_value(quantity))],
            vec![BookLevel::new(price(ask), quantity_value(quantity))],
        ),
    )
    .expect("fixture book event must be valid");
    OrderBook::apply_snapshot(
        None,
        &event,
        DurationNs::new(1_000).expect("fixture duration must be valid"),
    )
    .expect("fixture order book must be valid")
}

fn active_universe(at: TimestampNs) -> crate::universe::UniverseActivation {
    let snapshot = UniverseSelector::select(
        timestamp(0),
        [universe_candidate("BTC"), universe_candidate("ETH")],
    )
    .expect("fixture universe snapshot must be valid");
    UniverseSelector::activate(&snapshot, None, at)
        .expect("fixture universe activation must be valid")
}

fn universe_candidate(market: &str) -> UniverseCandidate {
    let depth = SidedDepth::new(usdc(50_000), usdc(60_000), usdc(70_000))
        .expect("fixture depth must be valid");
    UniverseCandidate::new(
        Market::new(market).expect("fixture market must be valid"),
        true,
        MarketDataAvailability::new(ListingState::Active, true, true, true, 20),
        HistoryQuality::new(30, decimal(995, 3), true, Decimal::ONE)
            .expect("fixture history must be valid"),
        UniverseLiquidity::new(
            usdc(5_000_000),
            usdc(1_000_000),
            Bps::new(Decimal::from(15)).expect("fixture spread must be valid"),
            DepthProfile::new(depth.clone(), depth),
        ),
    )
}

fn request(at: TimestampNs) -> RiskRequest {
    let tiers = MaintenanceTiers::new(vec![
        MaintenanceTier::new(usdc(0), None, decimal(25, 3), usdc(0))
            .expect("fixture maintenance tier must be valid"),
    ])
    .expect("fixture maintenance tiers must be valid");
    let snapshot = RiskSnapshot::new(
        at,
        at,
        usdc(100),
        digest('a'),
        digest('b'),
        digest('c'),
        digest('d'),
        digest('e'),
    )
    .expect("fixture risk snapshot must be valid");
    let constraints = VenueConstraints::new(
        3,
        usdc(1),
        usdc(500),
        usdc(500),
        Leverage::new(20).expect("fixture leverage must be valid"),
        tiers,
    )
    .expect("fixture venue constraints must be valid");
    let costs = ConservativeCosts::new(
        decimal(75, 5),
        decimal(75, 5),
        ImpactCurve::new(vec![
            ImpactBand::new(None, decimal(5, 4), decimal(1, 3))
                .expect("fixture impact band must be valid"),
        ])
        .expect("fixture impact curve must be valid"),
        decimal(1, 4),
        decimal(2, 4),
        4,
    )
    .expect("fixture costs must be valid");
    RiskRequest::new(
        snapshot,
        constraints,
        costs,
        RiskLimits::new(usdc(1), decimal(25, 2), decimal(25, 1))
            .expect("fixture risk limits must be valid"),
    )
}

fn candidate(market: &str, gross_edge: Decimal, at: TimestampNs) -> SignalCandidate {
    SignalCandidate::new(CandidateSpecification {
        strategy: StrategyKind::RulesOnly,
        market: Market::new(market).expect("fixture market must be valid"),
        side: Side::Buy,
        sleeve: Sleeve::FifteenMinute,
        decision_time: at,
        gross_edge,
        reference_entry: price(100),
        stop: price(99),
        target: price(102),
        time_exit: timestamp(i128::from(at.value()) + 1_000),
        snapshot_digest: digest('a'),
        universe_digest: active_universe(at)
            .universe()
            .expect("fixture universe must be tradeable")
            .digest()
            .to_owned(),
        history_digest: digest('d'),
        strategy_fingerprint: RULES_FINGERPRINT.to_owned(),
        explanation_json: "{}".to_owned(),
    })
    .expect("fixture candidate must be valid")
}

struct AcceptAll;

impl Strategy for AcceptAll {
    fn fingerprint(&self) -> &str {
        RULES_FINGERPRINT
    }

    fn accept_cost(&self, candidate: &SignalCandidate, quote: &CostQuote) -> CostDecision {
        CostDecision::Accepted(Box::new(OrderIntent::new(candidate.clone(), quote)))
    }
}

fn event_id(value: &str) -> EventId {
    EventId::new(value).expect("fixture event ID must be valid")
}

fn timestamp(value: i128) -> TimestampNs {
    TimestampNs::new(value).expect("fixture timestamp must be valid")
}

fn price(value: i64) -> Price {
    Price::new(Decimal::from(value)).expect("fixture price must be valid")
}

fn quantity_value(value: Decimal) -> Quantity {
    Quantity::new(value).expect("fixture quantity must be valid")
}

fn usdc(value: i64) -> Usdc {
    Usdc::new(Decimal::from(value)).expect("fixture USDC must be valid")
}

fn decimal(mantissa: i64, scale: u32) -> Decimal {
    Decimal::new(mantissa, scale)
}

fn digest(value: char) -> String {
    std::iter::repeat_n(value, 64).collect()
}
